name: kge
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyterlab=4.2.4
  - matplotlib=3.9.1
  - optuna=3.6.1
  - pandas=2.2.2
  - pip=24.2
  - polars=1.2.1
  - pyarrow=17.0.0
  - pytorch=2.4.0
  - pytorch-cuda=11.8
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
prefix: /home/rogertu/miniforge3/envs/kge
